/**
 * Make task_instances.master_id nullable with ON DELETE SET NULL.
 *
 * Motivation: the legacy `tasks` cascade-delete-recurring flow preserves
 * completed instances (status in {done, cancel, skip}) by clearing their
 * `source_id` before deleting the template row. In the new schema, the FK
 * (ON DELETE CASCADE + NOT NULL) would always delete those instances when
 * the master is dropped. That's a behavior regression — completed history
 * is valuable user data.
 *
 * Change: drop the existing FK, drop NOT NULL, recreate FK with
 * ON DELETE SET NULL. Callers that want to "detach" a completed instance
 * just update its master_id to NULL (helper: updateInstancesWhere);
 * deleting the master then cascades NULL-out on any remaining linked rows.
 */
exports.up = async function(knex) {
  // Drop the old FK (name generated by knex: task_instances_master_id_foreign)
  await knex.schema.alterTable('task_instances', function(table) {
    table.dropForeign('master_id');
  });
  // Make master_id nullable
  await knex.raw('ALTER TABLE task_instances MODIFY COLUMN master_id VARCHAR(100) NULL');
  // Re-add FK with ON DELETE SET NULL
  await knex.schema.alterTable('task_instances', function(table) {
    table.foreign('master_id')
      .references('id').inTable('task_masters')
      .onDelete('SET NULL');
  });
};

exports.down = async function(knex) {
  // Pre-flight: any NULL master_id rows block restoring NOT NULL. Delete them
  // (they're orphaned history in the old model anyway).
  await knex('task_instances').whereNull('master_id').del();

  await knex.schema.alterTable('task_instances', function(table) {
    table.dropForeign('master_id');
  });
  await knex.raw('ALTER TABLE task_instances MODIFY COLUMN master_id VARCHAR(100) NOT NULL');
  await knex.schema.alterTable('task_instances', function(table) {
    table.foreign('master_id')
      .references('id').inTable('task_masters')
      .onDelete('CASCADE');
  });
};
